### ISSUE TITLE
bazel: tests fail on "drake deprecated" warnings.

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#10]
(as we have in the cmake logic)

**Comment by EricCousineau-TRI** [comment]
A better way to do this is to make sure you have everything organized in one super package, and in that `__init__.py`, do the `warnings.simplefilter` to raise `DrakeDeprecationWarning` to an error.

**Comment by EricCousineau-TRI** [comment]
You could also cargo-cult Drake's existing unittest runner, and try to use something like that exclusively for your tests:
https://github.com/RobotLocomotion/drake/blob/5259cc0ae11add6d00d1d4baf1f1c2946ca624b0/common/test_utilities/drake_py_unittest_main.py#L105-L108

**Comment by RussTedrake** [comment]
fyi -- this bit me on https://github.com/RobotLocomotion/drake/pull/13785 which broke underactuated https://github.com/RussTedrake/underactuated/commit/f06499309b3ebf2fc927bc11d4ce89b3b4b3d858

**Comment by RussTedrake** [comment]
Adding `warnings.simplefilter` to the top of the output from `nbconverter` did the trick.  thanks @EricCousineau-TRI .
