### ISSUE TITLE
Issues with meshcat visualization in course colabs

### ISSUE THREAD

**Issue by wf34** [RussTedrake/manipulation#127]
I was taking manipulation course self-paced and today I saw the error, which never appeared before:
```
Tunnel 2306fa0eaf41.ngrok.io not found
```
I reproduce this issue in several notebooks and over few different internet options, available to me.
Was the visualization server taken down?

...github may be considered not the best place to raise this issue, so I apologize for that.

**Comment by ShigekazuIshihara** [comment]
Dear Prof. Tedrake and colleagues, students,

I am Prof. Shigekazu Ishihara, at the Prosthetics and Orthotics section of Faculty of Rehabilitation, Hiroshima International University. This autumn-winter term, I have utilized your course for the final part of robotics and sensing lecture (for application for robotic artificial limb) at my on-demand lecture in this difficult situation. 
Thank you very very much. 

We (I and students) faced exactly same problem which "wf34" mentioned.
I guess ngrok.io changed some tunneling feature or address.
Please give some clue to ease the problem.

Shigekazu Ishihara, Prof. PhD.
Hiroshima International Univ.

**Comment by ShigekazuIshihara** [comment]
we have to make account and set ngrok tunneling?

**Comment by ShigekazuIshihara** [comment]
Thank you very much.. Now I see ngrok works well!!

**Comment by wf34** [comment]
Thank you so much, the issue is resolved.
