### ISSUE TITLE
purge open3d dependency

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#130]
We don't use much of the functionality, so I only need to add a few more methods to Drake:
- [x] PointCloud::Crop (axis aligned bounding box)
- [x] PointCloud::Merge/[Concatenate](https://github.com/PointCloudLibrary/pcl/blob/2ef6ae2f860abb0f471cb8c8212e1d47068459e1/common/src/PCLPointCloud2.cpp#L49)
- [ ] nearest neighbors(e.g. via KDtree in flann or nanoflann)
- [ ] PointCloud::EstimateNormals (https://github.com/RobotLocomotion/drake/pull/17914)
- [x] PointCloud::VoxelizedDownSample (https://github.com/RobotLocomotion/drake/pull/17885)
- [ ] PointCloud::OrientNormalsTowardCamera (https://github.com/RobotLocomotion/drake/pull/17922)

**Comment by EricCousineau-TRI** [comment]
Curious - what's the negative impact of `open3d`? Just that it has a large footprint?

**Comment by RussTedrake** [comment]
1) i haven't been able to support it on mac for some time due to an incompatability.
2) converting back and forth between drake point clouds and open3d point clouds is unnecessarily confusing for students.
3) I'm barely using it!

**Comment by RussTedrake** [comment]
(plus the large footprint  ;-)

**Comment by EricCousineau-TRI** [comment]
Gotcha, that all makes sense, thanks for the explanation!

**Comment by RussTedrake** [comment]
I just confirmed, open3d doesn't appear to support python 3.10 yet (which is what Drake uses on mac)
http://www.open3d.org/docs/release/getting_started.html#development-version-pip

```
pip3 install open3d
ERROR: Could not find a version that satisfies the requirement open3d (from versions: none)
ERROR: No matching distribution found for open3d
```

**Comment by adamconkey** [comment]
Once this issue is addressed, will a pip install of this package be supported for Python 3.10 on Mac? I've currently been running into the problem you describe where it can't install due to not finding a supported open3d dependency.

**Comment by RussTedrake** [comment]
Yes, I believe that should work.  And i've completed converting all but one final pset question; this work should be complete by this weekend.

**Comment by adamconkey** [comment]
Thanks for this, I tried the pip install on MacOS today and it works great.
