### ISSUE TITLE
Failed import in qp_diff_ik.ipynb

### ISSUE THREAD

**Issue by flederbaysian** [RussTedrake/manipulation#139]
The first cell in the notebook lectures/qp_diff_ik.ipynb fails with:
```
ModuleNotFoundError: No module named 'manipulation.scenarios'
```

The issue is that the `manipulation_sha` passed to `setup_manipulation` was from before `manipulation.scenarios` existed. Changing the sha to 3081d6b95637d610634bced2d939b4b9e2b928eb gets the notebook working.

**Comment by RussTedrake** [comment]
i've update the shas.  Thanks.
