### ISSUE TITLE
add dockerhub post-merge integration 

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#147]
i believe it now requires an account; need to request an edu account from dockerhub.  Update: submitted request form on 2021/08/30

**Comment by JafarAbdi** [comment]
@RussTedrake Is this still blocked .? I worked on building docker images with GitHub actions & [docker packages](https://github.com/features/packages) (we could make it push to docker-hub, too), I can spend some time trying to integrate it with this repo if you want

**Comment by RussTedrake** [comment]
That's mighty kind of you.  The only blocker, i think, was getting my dockerhub edu account.  I think the setup now should be straight-forward enough.
