### ISSUE TITLE
[deepnote] duplicating a project does not duplicate the environment 

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#148]
When a user duplicates a project from my "share project" link, the Environment should get duplicated, too.  In particular, I need to duplicate:
- [x] the dockerhub link used for the docker image, and 
- [x] the tunneling option enable bit

**Comment by RussTedrake** [comment]
+@danzvara

**Comment by danzvara** [comment]
Both of these are bugs. Reported in our internal tracking, should get fixed soon

**Comment by danzvara** [comment]
Both should be fixed now!

**Comment by RussTedrake** [comment]
Hoorah.  Worked on my quick test.  Thanks!
