### ISSUE TITLE
[deepnote] can I share a link directly to an entry in the table of contents?

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#150]
It would be great to be able to share a link directly to a section of the notebook.  
![image](https://user-images.githubusercontent.com/6442292/131556000-f5fb9715-2bd3-45dc-91ec-d137e5839f3d.png)

**Comment by danzvara** [comment]
This should be possible - try doing a right-click on respective section and copy the link, it should point to that section

**Comment by RussTedrake** [comment]
Indeed.  Sorry I missed that!

**Comment by RussTedrake** [comment]
Unfortunately, I still don't think this will work as I hoped (allowing someone reading the text follows along by launching deepnote at the top, then clicking on the links in html to advance).  To do that, I would need to link to the future _duplicated_ project.
