### ISSUE TITLE
Broken link in reflected_inertia.ipynb

### ISSUE THREAD

**Issue by avalenzu** [RussTedrake/manipulation#19]
The link to drake.mit.edu is broken [in this section](https://colab.research.google.com/github/RussTedrake/manipulation/blob/master/exercises/robot/reflected_inertia.ipynb#scrollTo=0iKx8BDL_sj4). It tries to go to https://github.com/RussTedrake/manipulation/blob/master/exercises/robot/drake.mit.edu instead of https://drake.mit.edu

**Comment by hjsuh94** [comment]
Thank you @avalenzu ! #20 should have fixed this.
