### ISSUE TITLE
Interactive command cause trouble for autograder

### ISSUE THREAD

**Issue by buoyancy99** [RussTedrake/manipulation#194]
teleop_2d_direct(interactive=True) will cause EOF error for autograder due to calling `input()`.

A solution would be using slide bar (maybe ipywidgets) instead of input() for interactive mode.

See this piazza [post](https://piazza.com/class/l6s8p2f23ij7bz/post/18)

**Comment by RussTedrake** [comment]
We cannot use ipywidgets on Deepnote.  That's why I've added sliders to Meshcat.  We have JointSliders that work like PoseSliders, but using that would not have accomplished the learning goals of that exercise.

**Comment by RussTedrake** [comment]
Resolved.
