### ISSUE TITLE
A big question:how to use drake in real manipulator control 

### ISSUE THREAD

**Issue by 54WC** [RussTedrake/manipulation#242]
We know Drake is Model-Based Design and Verification for Robotics. If someone want to develop a software to control a real manipulator. Should he do it under Drake environment?  Of he want to use a part of drake software components(for example mathematical_program), in technique, can he wrap it as library into his own program?      
For a real robot control system, it might be a real time embedded system. Drake is a big program. Can they work together? 
Thank you very much!

**Comment by RussTedrake** [comment]
Yes, we use Drake on real robots in tight control loops all of the time. Drake as a library doesn't do any work to guarantee hard realtime.  But we often run our optimization-based controllers at hundreds of Hz (even up to a kHz). See Ch2 for some notes on the hardware interface (one option for doing this), and https://manipulation.mit.edu/station.html for some drivers if you want to replicate the narrow class setup.
