### ISSUE TITLE
BuildAndSimulate function in reflected_inertia.ipynb does not visualize diagram

### ISSUE THREAD

**Issue by achuwilson** [RussTedrake/manipulation#25]
```The implementation of GenerateHtml has been temporarily removed from Drake due to licensing restrictions.```
It just shows the  above message, while running on own machine.

**Comment by RussTedrake** [comment]
That warning is known, but the string we prepend should make it work again.  Are you running in a jupyter notebook where you would expect javascript to work inside the cell output?

**Comment by achuwilson** [comment]
I guess it was some hitch with JavaScript. Disabling and enabling JavaScript in the browser solved it. Thanks!
