### ISSUE TITLE
Typo in RRT nearest node computation?

### ISSUE THREAD

**Issue by horizon-blue** [RussTedrake/manipulation#271]
Hi Robotic Manipulation course staffs, it seems like there's a small typo in the computation of nearest node in RRT [on this line](https://github.com/RussTedrake/manipulation/blame/master/manipulation/exercises/trajectories/rrt_planner/rrt_planning.py#L58), where the update should be `distance = child_distance` instead of `child_distance = child_distance`. 

The same typo can also be found in the [RRT exercise notebook](https://github.com/RussTedrake/manipulation/blob/master/trajectories/exercises/rrt_planning.ipynb). Somehow it didn't cause an issue in there, but when we tried to adapt this RRT implementation for our project, this typo made RRT more likely to expand from the root instead of from the tree node that's actually nearest to the sampled configuration :).

**Comment by RussTedrake** [comment]
You're absolutely right.  Thanks for catching (and reporting) that.
