### ISSUE TITLE
Bug in AddCameraBox implementation?

### ISSUE THREAD

**Issue by sizhe-li** [RussTedrake/manipulation#272]
Hi Russ and course staff,

I think [the AddCameraBox function](https://github.com/RussTedrake/manipulation/blob/bd5b3bc87f9524951a8aeb91468fc16778017235/manipulation/scenarios.py#L280) has bugs.

In L280, `parser = Plant(parser)` should instead be `parser=Parser(plant)`?

Additionally, L288 should have `[0]` indexing at the end because `AddModelsFromString` currently returns a list of length one. 

Sizhe

**Comment by RussTedrake** [comment]
Indeed. Clearly, it's not being used.  I will zap it.
