### ISSUE TITLE
`pyzmq<25.0.0` dependency is not compatible with Python 3.12

### ISSUE THREAD

**Issue by siddancha** [RussTedrake/manipulation#387]
From DrakeDevelopers Slack: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1732125048711429

Currently, the `pyzmq` dependency is set to `<25.0.0` for Linux [[LINK]](https://github.com/RussTedrake/manipulation/blob/8d4c9eca374eaad5564a58d35de9f0d149af07bd/pyproject.toml#L58-L61). And Python3.12 is the default and officially supported version for Ubuntu 24.04 [[LINK]](https://drake.mit.edu/installation.html). Therefore, `pyzmq<25.0.0` must work with Python 3.12. However, that does not seem to be the case.

> The issue is that there don't appear to be any published binary wheels for pyzmq under python3.12 whose versions are less than 25, so pip install manipulation would try to build pyzmq from source, which would fail for a variety of reasons (I swapped out my G++ version, I installed an external libzmq to bind against, it still failed, but differently each time).

**Comment by RussTedrake** [comment]
It's possible that bumping deepnote to using 24.04 would resolve the conflict.  But i'm reluctant to do that in the final weeks of class. Perhaps we can try it just after the semester ends?
