### ISSUE TITLE
replace scikit-learn nearest neighbor with open3d

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#47]
and remove the (unnecessary) dependencies of scipy and scikit-learn 
will wait til pset 2 is fully submitted.

cc @hjsuh94

**Comment by hjsuh94** [comment]
Seems like a good idea. I also got the following error while trying to use scikit-learn in Docker: 
`RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb` 

which stopped after I did `pip3 install numpy --upgrade`. 

Strange, but it seems like the version installed by `sudo apt-get install python3-numpy` in `install_prereqs.sh` is not high enough? Would it be good to put a version requirement for `numpy` in `requirements.txt`?

**Comment by RussTedrake** [comment]
ugh.  i already did something similar for scipy to make CI happy.  i'm ok if you need to do it.

**Comment by RussTedrake** [comment]
@hjsuh94 -- i've made the change in my pose.ipynb.  can you propagate it to the exercises, and let me know?  then we can remove the build dependencies, too.

**Comment by hjsuh94** [comment]
Got it! I will make a PR after running some checks like uploading to Gradescope. 

Meanwhile, I think you have a typo in `pose.ipynb`. 
`distance  = np.linalg.norm(point_cloud_A[:,i] - point_cloud_B[:,i])` 

should be 
`distances[i]  = np.linalg.norm(point_cloud_A[:,i] - point_cloud_B[:,indices[i])]`?

**Comment by RussTedrake** [comment]
oops.  gulp.  that actually also revealed that i'm not actually using the distances anywhere.  So I've simply removed that part.  thanks for catching it!
