### ISSUE TITLE
bazel: set MPLBACKEND=Template environment variable for tests

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/manipulation#8]
(and re-enable the disabled tests)

obviously, the desired behavior is that `bazel run` shows the gui, but `bazel test` does not.

**Comment by RussTedrake** [comment]
marked this one as high priority, because I can start using bazel testing for at least part of my workflow locally once it lands.   (the other features are more "optional")

**Comment by jamiesnape** [comment]
Fixed in https://github.com/RussTedrake/manipulation/commit/de51127e641632ef58888bf0d5a1a1c432fcef79.
