### ISSUE TITLE
update open3d to v0.11.0

### ISSUE THREAD

**Issue by hjsuh94** [RussTedrake/manipulation#80]
From #79, Open3d is reverted to v0.10.0 due to:

https://github.com/intel-isl/Open3D/issues/2509
https://github.com/intel-isl/Open3D/issues/2508

Will need to update to v0.11.0 in the future as these issues are resolved.

**Comment by RussTedrake** [comment]
updated plan is to purge open3d entirely.

**Comment by RussTedrake** [comment]
duplicate of #130
